### ISSUE TITLE
Target for 1.0?

### ISSUE THREAD

**Issue by mattzollinhofer** [testdouble/standard#101]
I've been lurking for a while and keeping an eye on the issues for the past couple of months. As an interested passerby it doesn't feel like many new issues have been raised recently.

I'm curious if you have any target for when you'll decide to call it 1.0? Amount of time? Time since last issue? General intuition?

**Comment by searls** [comment]
It's definitely a judgment call. Because I view @samphippen's [rubyfmt](https://github.com/samphippen/rubyfmt) as a sister project of sorts for this one, we're trying to coordinate to ensure that the output of each agrees with the other. 

As a result, lately I've been thinking we should probably be coordinating with Sam to get them both to 1.0 in coordination (and as soon as we can, of course).

**Comment by mattzollinhofer** [comment]
Yeah I was wondering about that. Very happy to hear that you two are trying to stay in sync. I'm trying to decide when to introduce this idea to my team, who've had some struggles with rubocop style preferences. I think deferring the choice to standard/rubyfmt will go over well, but don't want to do it too early in the process. 

Thanks for your work on this and in the SW dev community in general!

**Comment by searls** [comment]
Sam and I talk a lot and I would be pretty shocked at this point if standard or rubyfmt at 1.0 generated such different autocorrection that anyone should wait to adopt standard until then. 

The variation from not having it during development would surely be greater than the variation between what it does now and what it does at 1.0

2019/04/03 19:31、mattzollinhofer <notifications@github.com>のメール:
