### ISSUE TITLE
Line length?

### ISSUE THREAD

**Issue by jswright61** [testdouble/standard#102]
There's a lot of great stuff in here to standardize formatting, but I've seen nothing to address when a line should be continued on the next line and how that should happen. The leading dot goes a long way but doesn't specify when.
What about long literals, when and how should they be broken up.
It seems omitting line length was a conscious choice but I'd like to understand why. When and how to continue lines has taken more code review time than it should

**Comment by searls** [comment]
The reason I omitted line length from standard is because no number is going to make everyone happy, and particular instances (especially in the case of fixture files full of densely packed, repetitive literals) different rationales will sway people. Because the "right" length is highly context-dependent, it didn't make sense for the tool to unilaterally declare when lines should break in such a way as to prevent being overridden (as standard is meant to be non-configurable).

**Comment by searls** [comment]
By the way, you might want to look at this issue for similar discussion for rubyfmt (which @samphippen and I plan to be designed to pair with standard) https://github.com/samphippen/rubyfmt/issues/45

**Comment by jswright61** [comment]
I think it's very important to have a line length setting - if you feel it's better to leave it to the other tool I can't really argue. I feel very strongly that it should be a setting somewhere  **AND** that it should be configurable.

**Comment by ibrasho** [comment]
@searls So there is no way to pass a line length limit to Rubocop when using standard currently?
