### ISSUE TITLE
Should standard run performance checks?

### ISSUE THREAD

**Issue by searls** [testdouble/standard#105]
Rubocop 0.68 will remove the `Performance` namespace of cops. Should Standard pull in the `rubocop-performance` gem and continue running most `Performance/*` checks?

For now, I've locked down the gemspec to `~> 0.67.1`.

Reference: https://github.com/rubocop-hq/rubocop/issues/5977

**Comment by czj** [comment]
IMHO the notion of performance is excluded because standard is defined as a "style guide, linter, and formatter". Style, not performance.

However, if this definition can evolve, applying performance best practices would be really great. Maybe by passing an optional `--performance` ?

Performance constraints might make the code less maintainable, readable, so we need to carefully draw a line between what's acceptable and what's too restrictive. There's the issue of pure speed VS memory allocation, different speed across different Ruby runtimes, etc.

(and thanks again to you and all contributors for the fantastic work on standard !)

**Comment by searls** [comment]
@czj If a particular bit of code will result in wildly bad performance, I think that falls under any definition of "lint" I have ever come across, FWIW

**Comment by czj** [comment]
Oh sorry. My native langage is French so I've only use linter in programming context, thinking about the original definition of "a machine for removing the short fibers from cotton seeds after ginning" which mapped in my mind these short fibers to "ugliness in style".

I think you used the proper term with "wildly bad". I've re-read many `Performance` cops, they are reasonable and catch these kinds of bad performance.

Having performance cops in the `standard` gem would prevent having to use another tool to detect these code smells. That would make a great workflow.

**Comment by mattpolito** [comment]
@searls I agree. If someone has taken the time to say 'this helps prevent shooting one's self in the foot' regarding performance... then it should be included in a lint. Seems the only thing to consider would be... are they considered 'standard' practice?

**Comment by searls** [comment]
I have decided yes, we should, because @mattpolito said so

**Comment by searls** [comment]
This was inadvertently closed!

**Comment by ktopolski** [comment]
I do agree here. Checking performance issues imho should be linter concern. Also, as we aim for this project to become "the standard", community could definitely use performance checks by default.

**Comment by pablocrivella** [comment]
@searls I see that the gemspec already requires `rubocop-performance` (https://github.com/testdouble/standard/blob/master/standard.gemspec#L22) and so does the configuration file (https://github.com/testdouble/standard/blob/master/config/base.yml#L2) so I think this issue could be closed
