### ISSUE TITLE
Consider disabling Layout/IndentHeredoc

### ISSUE THREAD

**Issue by penelopezone** [testdouble/standard#113]
essentially allowing users to specify the type of heredoc that they want, not having to indent if they don't want to.

**Comment by searls** [comment]
Would love to see some more discussion about this. At first blush I can imagine a custom cop that might do things a little differently without disabling heredoc indentation opinions entirely

**Comment by bolshakov** [comment]
Unfortunately, there is no such method `#strip_heredoc` in Ruby standard library and suggestion to add active_support to dependencies for that purpose not always possible/desirable.

**Comment by searls** [comment]
Sam you showed me the case that needed this, but apart from pretty esoteric cases in rubyfmt and gel, it really seems like something that the vast majority of libs don't need—an inline or method-level exception might be more appropriate.

I say this because I think the squiggle-heredoc is still relatively unknown about rubyists and the net good of promoting it for folks outweighs the risk _if the above is true_ and only a handful of cases truly must not have indented heredoc content.

Do we have more examples of when indents are inappropriate?

**Comment by samphippen** [comment]
I meannnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn, there was also a semantics change in indented heredocs somewhere between 2.3 and 2.6 that I need to track down. I'm ok with forced indented heredocs if we can determine them to be consistent.

**Comment by searls** [comment]
inconsistency demo plz!

**Comment by samphippen** [comment]
paging @jcoglan

**Comment by fdr** [comment]
FWIW I often use heredocs in cases where indention adds long lines and opportunity for error, e.g. bodies of configuration files. So count me as -1 on obliged indenting.

**Comment by penelopezone** [comment]
I am convinced we shouldn't do this.
