### ISSUE TITLE
After 1.0, will standard continue to update alongside rubocop?

### ISSUE THREAD

**Issue by onebree** [testdouble/standard#122]
I understand that standard is set up to opt-into cops. While working on a PR related to cop settings, I noticed a few things:

There are plenty of cops omitted from `config/base.yml`, but without an attached issue/commit discussing _why_. For example:

  + All things metrics
  + Naming/PredicateName
  + Naming/RescuedExceptionsVariableName
  + Performance/RedundantBlockCall

There are already a couple of cops added, or renamed, since rubocop 0.67:

  + 0.68: Rename `Layout/FirstParameterIndentation` to `Layout/IndentFirstArgument`
    * This one in particular tripped me up while working on my PR. I was referencing the latest rubocop docs page, rather than the config file at version 0.67
  + 0.69 - Add new cop `Style/NegativeUnless` that checks for unless with negative condition

So, given that rubocop is also pre-1.0, how will standard grow alongside it, if at all? I guess it's unclear whether cops were opted out of by intention, or by accident. And I think clearing that up somewhere (maybe a running list of opted-in and opted-out docs?) would help people researching this as an alternative to custom rubocop configs, or even contributors like myself trying to understand the project more.

Thank you!

**Comment by ktopolski** [comment]
Metrics are omitted on purpose, please see #102 . The plan is to grow along the rubyfmt which will take care of metrics IIRC.

I'm not so sure about other cops tho, probably we need to wait on @searls input here.

Cheers guys

**Comment by searls** [comment]
Hi Hunter, thanks for opening this issue.

To be honest, I think a lot of the sense of informality that you're describing is a symptom of the fact that Standard is a linting tool _from a group of people who don't care too much about style guides_. Because the primary goal Standard sets out to solve is not "establish One True Style", but just to avert bikeshedding on teams, the answer to 80% of the configurations we've landed on are with one of these rationales:

• Most people don't care or it doesn't matter (e.g. Arbitrarily picking one `Enumerable` method over an alias method)
• It can't be applied reasonably in 100% of cases, so it's better to turn it off than to enforce it and require people to figure out how to work around it (e.g. every single `Metrics/*` cop, AFAIK)
• There's an obviously "correct" choice, because the cop pushes people away from a deprecation, performance risk, unsafe code execution, likely mistake, etc. (e.g. [Lint/SafeNavigationChain](https://rubocop.readthedocs.io/en/stable/cops_lint/#lintsafenavigationchain))

The other 20% have been relatively painful judgment calls that are things that improve readability or decrease git churn when they're enforced consistently, and those have taken up 95% of the our time maintaining Standard. Searching the GitHub repo is unfortunately the best way to see how these decisions were litigated. 

I can only speak for myself, but the reason I haven't contributed to a tidy document of inclusions/exclusions is mostly a result that the litigations themselves aren't as valuable to me as that they happened and we went with the plurality of reasonable feedback in each case. This is how I wound up maintaining a linting tool that I mostly disagree with on the merits (since I'm on team hashrocket, team trailing dots, team no-trailing commas, etc.)

If you're interested in helping out by buttoning up the project by doing things like better documenting our [base.yml](https://github.com/testdouble/standard/blob/master/config/base.yml) file and fixing the `EnforcedStyle` values, for example, that'd be welcome and valuable IMO

**Comment by ktopolski** [comment]
seems like something I can help with in the next day or two

**Comment by onebree** [comment]
@searls thanks for the reply! What you said makes a lot of sense. And in fact, the PR I am working on will be adding `EnforcedStyle` values to each rule :-) If you want to help out with this, @ktopolski, LMK! I have some WIP changes locally.

But I'm not sure if my original question was addressed. Standard right now points to rubocop 0.67, with a current PR pointing to 0.71 or so. Does this project have the expectation to update when rubocop updates? For example, considering to opt-into newly added cops?

**Comment by searls** [comment]
Yes, sorry, we want to stay current with rubocop for as long as we are able to, hence @yez's PR to upgrade us. I don't keep a close eye on what cops are being added to rubocop as its version increments, so we'll probably need folks like yourself to propose turning them on if they're good.

**Comment by ktopolski** [comment]
sure why not, let's pair program on it @onebree  :)

**Comment by onebree** [comment]
@ktopolski If you want to help out, I pushed a WIP commit to my fork. If you want maintainer status on my fork, LMK, I welcome the help :-)

https://github.com/onebree/standard/commit/d9f025432c7c82e475f8210615797d37b1597e2f
