### ISSUE TITLE
First-class support for rubocop-daemon (or maybe a standard-daemon fork?)

### ISSUE THREAD

**Issue by ndbroadbent** [testdouble/standard#137]
I love using the `formatOnSave` option in VS Code. This works great for Prettier when I'm working on JS, because Prettier is really fast. RuboCop is not so fast, and it takes a long time to start (before it even begins auto-formatting files.)

[rubocop-daemon](https://github.com/fohte/rubocop-daemon) is one solution, and it keeps a copy of RuboCop running as a daemon. I also [wrote a bash wrapper script](https://github.com/fohte/rubocop-daemon/blob/master/bin/rubocop-daemon-wrapper) that is super fast and interacts with the daemon via `netcat`, so the auto-formatting speed is on par with Prettier.

I saw the issue about [editor support for VS Code](https://github.com/testdouble/standard/issues/44), so I thought I should mention `rubocop-daemon`, because a lot of people might want to start using `formatOnSave` for Ruby, and I wouldn't be able to handle it without `rubocop-daemon`. I would even propose including `rubocop-daemon` as a dependency, so that we speed up everyone's experience out of the box. It would be really nice even if you run standard from the CLI.

Anyway, thanks for all your work on standard!

**Comment by searls** [comment]
This is a great idea! How would you recommend moving forward here? Is it enough to document how to use the daemon in conjunction with standard? Is there a feature that standard should build out?

**Comment by ndbroadbent** [comment]
I think at least some documentation would be awesome, so that people know that this is an option for speeding up RuboCop. 

It would also be really cool if standard came with some out-of-the-box support for rubocop-daemon to speed things up by default. I don't know if that would practical for the CLI usage, because it's not possible to add a bash script (or any program) to the user's PATH when you install a Ruby gem. Rubygems only allows you to set up bin executables that are executed with Ruby, so you can't get the big performance win with a bash wrapper (or maybe a Go wrapper in the future.)

I've also been wanting to add rubocop-daemon support directly to the VS Code extension Ruby, but unfortunately I haven't had time to work on that. But if I or someone else does work on that, it would be good to make sure this also works with standard.

**Comment by searls** [comment]
As a starting point, if you can get standard working with rubocop-daemon, even if it's a little hacky, I'd love to have a section in the readme on how to do that

**Comment by wadetandy** [comment]
I ran into this same need last week, and have just pushed up [a branch](https://github.com/wadetandy/standard/tree/rubocop_daemon) which adds a `--rubocop-daemon` flag to standard which will have it talk to the deamon instead of running directly with rubocop internals (can also set `runner: rubocop_daemon` in your `.standard.yml` file).  Still needs testing and I'm sure I'm not passing all options down to rubocop correctly, but it mostly works.  This doesn't add rubocop-daemon as a dependency so it assumes you've installed that gem for now.

Unfortunately in trying it integrated with vscode's `formatOnSave`, it's not much of an improvement over what I had previously, as the bulk of the delays in running things are in startup. I'm seeing significant delays introduced both by my RVM setup as well as as general ruby startup time and the binstub added by rubygems. I think the most successful version of this would either add standard to the capabilities of `rubocop-daemon` or create a similar `standard-deamon` project.

**Comment by searls** [comment]
I think @wadetandy (👋) is probably right here that the vast majority of time spent is in startup/loading costs, especially because RuboCop (and therefore Standard's) file caching at run-time is pretty aggressive/effective. I think ultimately this should emerge via configuration in rubocop-daemon (e.g. specify a `bin` field) or as a fork (less desirable since it'd have to be maintained for what'd amount to—one would hope—a few lines difference)

**Comment by camilopayan** [comment]
I think this has essentially landed in Standard since v1.13.0 since [Rubocop shipped `--server`](https://metaredux.com/posts/2022/07/26/rubocop-serves-much-faster.html#fnref:1) so you can run `standard --server` and it will start the Rubocop server with the Standard config.
