### ISSUE TITLE
standard doesn't include bugfixes from rubocop 0.73

### ISSUE THREAD

**Issue by raorao** [testdouble/standard#139]
We're running into an issue where we want this fix (https://github.com/rubocop-hq/rubocop/issues/7170), which is released in rubocop 0.73. 

Are there plans to update the version of rubocop this library depends on?

**Comment by searls** [comment]
Sure, could you send a PR that updates standard to latest and we can see
how the build looks as a first step?

Standard is only pessimistic about which version of rubocop it locks to,
because sometimes rules and options will change such that the same version
of standard will behave differently depending on which transitive version
of RuboCop happens to be installed.

**Comment by raorao** [comment]
yup, happy to! just wanted to make sure i wasn't stepping on any toes 😅 .
