### ISSUE TITLE
Change autocorrect behavior of Lint/UnusedBlockArgument

### ISSUE THREAD

**Issue by searls** [testdouble/standard#14]
Currently the autocorrector of `Lint/UnusedBlockArgument` (and its equivalents) will prepend a `_` in front of any unused variable.

Example:

```ruby
items.each_with_index do |item, i|
  puts item
end
```

Will be autocorrected to:

```ruby
items.each_with_index do |item, _i|
  puts item
end
```

That `_i` seems bizarre and out of place, and I've never seen a human write Ruby like this to indicate a variable is unused. If we override the autocorrector to just change the variable to `_`, would it be any less safe? If that change would not be safe, should we just turn off this cop?

**Comment by JoshTGreenwood** [comment]
related:

`Lint/UselessAssignment: Useless assignment to variable - `result`. Use `_` or `_result` as a variable name to indicate that it won't be used.`

**Comment by jasonkarns** [comment]
I'm for renaming to `_`, since it's the idiomatic "unused" var.

However, the `_` is only really necessary for blocks if filling an argument position ahead of args that _are_ used. Trailing arguments don't need to be placeholders, so it should just be removed entirely, IMO. If that's possible, automatically, great. But I'd say the rule should suggest removing the variable entirely if it's at the end.

**Comment by grantbdev** [comment]
> That `_i` seems bizarre and out of place, and I've never seen a human write Ruby like this to indicate a variable is unused.

@searls As a human who does this, I'd say the benefit of doing it this way is clarity to future readers about what the unused variable is for in the same way you want to use descriptive variable names for stuff you do use. If you do then need to use it, the find and replace for something like `_changes` or `_options` is more likely to be easier than just replacing specific occurrences of `_`. 🤷‍♂️ 

That said, in my RuboCop usage I have turned auto-correct off for this because it's particularly annoying to have executed on save in the middle of WIP code.

**Comment by clockworkpc** [comment]
> That said, in my RuboCop usage I have turned auto-correct off for this because it's particularly annoying to have executed on save in the middle of WIP code.

How do you turn off autocorrect for this?  I have the same annoyance.
