### ISSUE TITLE
Using loop do..end instead of begin..break..end breaks with locally defined vars

### ISSUE THREAD

**Issue by ashleyHutton** [testdouble/standard#148]
Original:
```
begin
  uid = Uid.new(6)
  results = self.class.where(token: uid)
end while results.length > 0
self.token = uid
```
After standard:
```
loop do
  uid = Uid.new(6)
  results = self.class.where(token: uid)
  break if results.length <= 0
end
self.token = uid
```

Since the original style we had wasn't using a block, the variable `uid` defined inside of the `begin` was accessible to us outside of the loop.

Using the `loop do` syntax meant that the `uid` is out of scope when we're outside of the block, so `self.token = uid` throws an error since `uid` is `nil`.

Update: We noticed this was not automatically corrected by the linter, so the manual change is actually what broke the code. But should the linter have a warning that the `uid` variable is not accessible outside of the block?

**Comment by searls** [comment]
For what it's worth, if you try to undertake this refactor on the above example, you'll have an intermediate lint failure, it looks like.

When I switched a similar code example to a loop:

```ruby
results = []
loop do
  uid = 6
  results << :lol
  break if results.length < 10
end

token = uid
```

I get this intermediate error, indicating that `uid` is out of scope, which is better than just failing at runtime:

```
  foo.rb:9:3: Lint/UselessAssignment: Useless assignment to variable - `uid`.
```

That said, I feel like the value of `Lint/Loop` is kinda iffy overall. I have to admit in the ~14 years I've been writing Ruby, I don't think I've ever used _either_ `loop` or a `begin…while` loop, so I feel unsure of whether to eliminate the rule or not in this case. Would love some feedback from others about the issue to help us decide what to do. 

[In any case, thanks for raising the issue Ashley! It's definitely not ideal right now and you did a good job explaining what's going on and how it caused you friction.]

**Comment by olivierlacan** [comment]
I was about to say that it would be fine for Standard not to have an opinion on this since I also have rarely used `loop` or `while` in Ruby in a decade of practice but @ashleyHutton's first example looks like a clear case of hidden loop in my mind, so it feels like if anything the broken suggestion should be fixed instead of removing this actually good refactor suggestion.

Assuming this is possible to suggest: 

```ruby
loop do
  uid = Uid.new(6)
  results = self.class.where(token: uid)
  if results.empty?
    self.token = uid
    break
   end
end
```

Assuming this `where` is from ActiveRecord, maybe a more context-specific suggestion would be: 

```ruby
result = self.class.find_or_initialize_by(token: Uid.new(6))
```

Big assumptions I'm making here: 
- you don't *actually* expect multiple results from the `where` (because maybe there's some unique validation on the `token` attribute/column)
- you don't need to use the `uid` variable for anything else
- `self` doesn't *have to be instantiated* outside of this code

The more I think about it, the sillier my suggestion seems considering how much context Standard would need to extract in order to recommend a change like this. Oh well, I hope it helps anyway. 🤷‍♂
