### ISSUE TITLE
problem with Lint/Void and setter methods

### ISSUE THREAD

**Issue by will** [testdouble/standard#206]
I have a class I'm writing a setter for, but I'm actually storing some transformation of the value. The point of this setter is to hide the details of what's happening and give a better interface. 

My understanding is that it's customary for setter methods to return the value that was passed in:

``` ruby
class Foo
  def some_setter=(t)
    @val = run_some_code_and_change_type(t)
    t
  end
end
```

However this fails because of `Lint/Void` in standard 0.7

```
/tmp> standardrb a.rb
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
  a.rb:4:5: Lint/Void: Variable `t` used in void context.

Notice: Disagree with these rules? While StandardRB is pre-1.0.0, feel free to submit suggestions to:
  https://github.com/testdouble/standard/issues/new
/tmp [1]> standardrb --version
0.7
```

I'm not 100% sure if the right thing to do is return the same thing that was passed in instead of what it ends up being. It's hard to think up places to check for precedent.

**Comment by jmkoni** [comment]
I think you probably want to just return the updated value since setters don’t usually return anything (in non-Ruby land at least). The rule is missing that you are setting this to an instance variable (might be worth opening up a bug on rubocop for this), so it only sees you doing an action then ignoring it.

**Comment by will** [comment]
Ok thank you!
