### ISSUE TITLE
Fetch Argument Standard Style Issue

### ISSUE THREAD

**Issue by Austio** [testdouble/standard#232]
Hello, 

Using standard RB and reporting a disagreement with style

```
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
  app/controllers/api/public/search_controller.rb:15:12: Style/RedundantFetchBlock: Use `fetch(:limit, 10)` instead of `fetch(:limit) { 10 }`.
```

This style is telling me to prefer `params.fetch(:limit, 10)` over `params.fetch(:limit) { 10 }`

These are fundamentally different things, passing a fallback argument to fetch will cause the argument to be evaluated in order to pass the value.  This is not a problem with numbers, but with expensive methods (reference to a db call or api call) this can cause really unnecessary work if the fetch is a hit.   Using the block syntax will not cause the value to be evaluated until the fetch is a miss.

If we are going to push people to 1 syntax or another, we should do the safer block way so that people who are not familiar with the language are not tripped up or remove this rule altogether.

Contrived example of using block to lazy eval a method
```
[1] pry(main)> def foo; puts 'called'; 5; end
=> :foo
[2] pry(main)> foo
called
=> 5
[3] pry(main)> bar = { baz: 1 }
=> {:baz=>1}
[4] pry(main)> bar.fetch(:baz)
=> 1
[5] pry(main)> bar.fetch(:baz, foo)
called
=> 1
[6] pry(main)> bar.fetch(:baz) { foo }
=> 1
```

**Comment by searls** [comment]
But isn't the rule smart enough to know if the block is deferring execution of a callable versus just returning a literal? Correct me, but taking your example into a `foo.rb` file like this:

```ruby
def foo
  puts "called"
  5
end
bar = {baz: 1}

bar.fetch(:baz)

bar.fetch(:baz, foo)

bar.fetch(:baz) { foo }
```

And standard exits cleanly against it, allowing all forms:

```
$ standardrb foo.rb 
$ echo $?
0
```

Closing unless there's an edge case that this rule does cause (in which case, I imagine rubocop would be interested in hearing about it upstream since I believe this is considered a safe autocorrect by them)
