### ISSUE TITLE
RUBOCOP conflicts 

### ISSUE THREAD

**Issue by MuhammedYousryKamel** [testdouble/standard#273]
I have some Rubocop rules in the rubocop.yml file and need the standard gem to follow these rules so what should I do?
I need to change the rules inside the config/base.yml file

**Comment by searls** [comment]
I'm sorry @MuhammedYousryKamel, but this usage isn't supported. Standard does not allow you to customize the rules, in order to encourage consistency across teams and projects.

You might find [this post](https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard) helpful, particularly the part about `inherit_gem`
