### ISSUE TITLE
Integration with rubocop-minitest

### ISSUE THREAD

**Issue by davidwessman** [testdouble/standard#276]
Hello, thank your for a fantastic gem!

1. What would be the best way to enable some rules from `rubocop-minitest` in standard?
2. Would it make sense to add some confguration for this to standard itself? 
    Or be able to combine it with another gem?

**Comment by jmkoni** [comment]
Hi @davidwessman! We don't officially support this, but there is a guide that can help you that we link to in the readme (https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard). We are looking into possibly having a standard-rails (#266) and, once we finish that, we might consider adding a similar functionality using rubocop-minitest. It would have to be separate (like the rails gem would be) since not everyone uses minitest :)

**Comment by davidwessman** [comment]
Thank you for the link!
Separate support for it in the future would be great.
