### ISSUE TITLE
Binary name 'standard' conflicts with standardjs

### ISSUE THREAD

**Issue by garybernhardt** [testdouble/standard#3]
Anyone who uses both tools is going to have two 'standard' binaries, which seems very bad. I humbly suggest the name 'nonstandard'.

**Comment by searls** [comment]
This is something I hemmed and hawed about while writing it. In truth, I've never done nor seen anyone globally install StandardJS, which means its bin is always sequestered in `node_modules/.bin`. Any reference to `standard` will be prepended as such when invoked from a package script, which is far and away the most common way I know it to be invoked.  (I wish things were so tidy in Rubby-land, but sadly all CLIs hit the user's normal path and I don't know a nice way around that.)

As a result, I decided to throw caution to the wind and start with `standard` and see if it causes anyone _actual_ problems and whether those can be remedied (the gem ships with a disambiguating `standardrb` bin as well). What I'd ideally prefer is a CLI smart enough to apply standard for multiple target languages rather than take a different name that's aiming to be the same thing. If that idealism proves foolhardy, then I'll cave and change the name to something.

**Comment by searls** [comment]
cc/ @feross since his opinion matters here a lot, and @jasonkarns because I already roped him into this discussion offline

**Comment by garybernhardt** [comment]
node_modules/.bin is on my PATH, and it will always come before the Ruby bin path because the latter is set dynamically.

**Comment by jasonkarns** [comment]
What was the over/under on how long the assumption of "node peeps run bins through npm scripts" was expected to last unchallenged?

**Comment by feross** [comment]
I don't feel super strongly.

A decent number of people install StandardJS globally though it's not how we recommend it to be used. One good reason that people install it globally is because they frequently format code in projects that don't have StandardJS (or any linter) as a local dependency. 

If you think the overlap between userbases is likely to be nontrivial, then I foresee a lot of people opening issues here about it in the future. Up to you how to proceed.

**Comment by jasonkarns** [comment]
Another point to take note of... since Rails 4 or 5, it's becoming much more common for ruby cli binstubs to be created locally to the project and even versioned.

So whether it's prevalent or not, it might be a nice side effect of pushing the practice that npm modules be invoked through npm-scripts (or npx) and gem clis invoked through `bin/` binstubs.

**Comment by garybernhardt** [comment]
I don't like it. Let $PATH be $PATH; this is why it's an environment variable and not a set of locations hard-coded into the shell. The Unix way is not to produce many tools with the same name and then demand that users never have them on $PATH.

**Comment by olivierlacan** [comment]
I do see the possible confusion, but I also love the idea of one ... standard tool which could be smart enough to tell me:
> Oh hi buddy, this isn't a Ruby codebase, you probably meant to use the other standard for scripts made with ☕️ 

I figure, sure, it's error-prone. But this can't be the first time two development tools from two language communities have the same executable name. Also I love love love `which -a` for this. I can have two versions of a thing on my `$PATH`. @garybernhardt's `node_modules/.bin` version of `standard` will only suck in codebases that have both the JS `standard` and the Ruby `standard`. I guess it's not that uncommon, but in those cases it seems like `standardrb` is there for the rescue. Despite the added cognitive load.

The README recommends a `Gemfile` install so I would never have thought of using `standard` directly without `bundle exec`. I do the same with `rubocop` because I don't want to accidentally be running a different version of Rubocop than the one bundled by the project and get a bunch of weird warnings. 

I also agree with @jasonkarns that Bundler-enabled binstubs are more common these days. 

Funny enough after using `npx` in a few JS codebases this makes me year for an `rx` command that wraps `bundle exec`. Thanks for the motivation to create yet another useless gem. 😆

**Comment by searls** [comment]
Appreciate all this input. (I suspect that on the road to 1.0.0, this thread will be chatty as we decide what to do so I encourage anyone unsubscribe/unwatch if they don't love getting emails.)

For now, I think Gary's concerns all seem significant. The only reasons I haven't already yanked the `standard` bin are:
* I personally get confused when a gem name doesn't match its binary name
* I really like the gem name because I think the Standard brand is good and should fan out beyond JavaScript because its anti-bikeshedding message is basically right (And a gem name like `standardrb` would rankle me because modules with `rb` in them are so counter-conventional; it would make this module come across as subordinate to StandardJS in a way that I don't think anyone wants or intends)
* I would love to see this push me to create a meta `standard` bin that'd run each program across multiple languages for a given project. The idea of a multi-language standardized linter is attractive to me since most of my projects contain at least two languages 

I have tested this locally in projects that now use both standards and have not had any issues, so I want to wait until this causes actual errors for users to better understand the scope of the impact it might have on folks as well as how narrow a prescription we can provide.

Current thinking is:

- [x] [Explain on the README](https://github.com/testdouble/standard#what-if-i-also-have-standardjs-installed) that `standardrb` is a thing
- [x] [Send a  PR](https://github.com/standard/standard/pull/1224) to StandardJS that adds an analogous `standardjs` alias bin
- [ ] [Add a rake task](https://github.com/testdouble/standard/issues/4) for easy Rake usage
- [ ] Solicit feedback from early users and track it closely
- [ ] Start spiking a meta-`standard` bin that would actually detect and execute both programs for projects that contain both Ruby & JavaScript

And, to be clear, if this becomes a real problem for users I suggest we give up and yank the `standard` bin from StandardRB and leave `standardrb`

**Comment by piotrmurach** [comment]
A bit of freeflowing thinking based on my experience building Ruby command line tools. 

I'm with @garybernhardt on this issue in so far as Unix philosophy goes. A lot of dev tooling achieves its magic by shimming and modifying the `$PATH`, however, this gem probably shouldn't rely on this to be the case. Skipping any friction here would be really good, especially for first time users.

@searls I don't envy you, naming things is hard! One thing that I would like to point out is that the **unwritten** rule of requiring the binary name to match the gem name doesn't have to be obeyed rigorously. For example, `bundler` the tool has binary `bundle` which perfectly conveys the action of bulding gems. Similarly, the `standard` gem could follow the pattern of using verb for action, e.i. `standardize` and an alias `standardise` to keep British developers happy as well. I personally find `standardrb` to be a bit clunky but it may be a good enough solution for the world domination you're planning when other language implement `standard` solutions. 

Anyhow, thanks for creating this gem! 👏

**Comment by garybernhardt** [comment]
There have been three possibilities suggested in this thread:

* Name the binary "standard". As more of these projects are created, every language ends up with a "standard" binary, I guess? Projects involving four languages have four binaries named "standard". $PATH, which has worked since the beginning of time, and still works today even in projects using NPM and Bundler and so on, stops working.
* Give the binary a different but language-independent name like "standardize". This solves the problem today, but doesn't solve the above problem with multiple languages. Is the third one named "standardify"? What's the fourth one named?
* Name the binary after the language that it's standardizing. This is the only naming scheme that scales.

AFAIK, this project is the one that's generalizing the name "standard" across multiple languages, so I view it as this project's job to set the convention. I really don't want a future where we have dozens of binaries with the same name, all doing different things, sometimes used in the same project, such that $PATH can't actually function. AFAIK, that's unprecedented in the history of Unix.

**Comment by searls** [comment]
I chewed on this while I was AFK for the last week and decided to bite the bullet now and change the binary name from `standard` to `standardrb` while retaining the gem name `standard`. The included rake tasks will continue to be named `standard` and `standard:fix`, and the namespace for the API will remain under a module `Standard`. Related, any time it might be ambiguous which Standard program someone is talking about (or invoking), we will say "StandardRB" in prose (the README mostly does this already).

Version 0.0.13 and later will warn when `standard` is invoked, and in a couple weeks I'll cut a release that errors out, and soon after a release that removes the bin entirely.

I looked into building a meta-tool to aggregate the results and outputs of 2 or more standard programs (as an addition to StandardJS), but everyone quickly agreed it'd be more headache than it would be worth. Better to keep the names separate, tied to the language they serve, etc. That aggregation tool already exists in the form of UNIX, anyway (e.g. `standard && standardrb`, etc).

Calling this fixed for now, I've set up timers to remind me to cut the next two releases over the next four weeks
