### ISSUE TITLE
rule for parentheses around parameters

### ISSUE THREAD

**Issue by tbsvttr** [testdouble/standard#318]
In our team, we have regular discussions about the parentheses of parameters: omitting them or not. Standard should do a standard for that. ;)

**Comment by searls** [comment]
Apologies, but we're not going to enforce parentheses around arguments on method invocations at this time.

I appreciate the sentiment, but there are so many situations where Ruby is written in a DSL (even just a configuration block) where parentheses would look _anything but_ standard (imagine all the static configuration at the top of a Rails model or controller; those are just class method calls). Making the opposite rule would be just as problematic, because there are plenty of situations where parentheses are needed in order for code to be interpreted correctly.

**Comment by gregorw** [comment]
@searls My team and I love the Standard philosophy which is: 

> The whole point of Standard is to save you time by avoiding bikeshedding about code style.

The issue we are having is that Standard doesn’t make enough bold decisions. It’s not opinionated enough. When Standard doesn’t decide on a rule — e.g. concerning parentheses — it is left to each and every team to have the discussion. This is against the idea and promise of Standard.

What do we do?

ps: We would love to use Standard since it is Ruby and we are already familiar with Rubocop. It’s quite sad that our team is now also considering alternatives (such as Prettier) which may be more opinionated and therefore avoids more discussions.

**Comment by searls** [comment]
I can't see how it would be possible to enforce a firm rule on this issue that wouldn't create contexts where Ruby no longer felt like Ruby.

If one insists on enforcing ommitted parens, all sorts of normal APIs (`add(4, 5)`) will look strange in certain contexts, and things like chaining method calls could result in multiple lines of git churn that'd essentially force people to rely on the auto-fixer to format their code, because it'd be too much hopping around otherwise (a secondary goal I have with Standard is that its strictures also be natural to type, front-to-back. Most Ruby I write at this point is standard-compliant before the linter runs). Additionally, since enforcing the presence of parens would be more popular generally (and especially more popular among the constituency of people who enjoy enforcing things), you'd have a lot of people unhappy about that choice.

On the other hand, if one insists on enforcing that parens are always included, pretty much every DSL in use today in Ruby—from minitest assertions to Rails routes to factorybot factories—would suddenly be littered with a bunch of parenthetical noise for no benefit at all beyond someone's satisfaction of knowing that there is only one true way for the syntax to be expressed. If that extreme is someone's end game, I think that beyond a certain point you'd be better off working in something like Go than Ruby.

Ruby's ability to express both humdrum functional APIs and naturally legible DSLs in a single, simple programming language is a remarkable strength I would hate to see diminished. I have not yet heard of an even more compelling benefit that would be realized by enforcing all method definitions/invocations to either use or not use parentheses.

**Comment by al2o3cr** [comment]
For comparison, Elixir's `mix format` _does_ enforce parentheses - but it has an escape hatch via the `locals_without_parens` option that allows paren-less use of the [DSL-like things from `Kernel`](https://github.com/elixir-lang/elixir/blob/b166e8e18429fa3f8d9656c8733fa7413abe6d48/lib/elixir/lib/code/formatter.ex#L57-L140) as well as an extension point for libraries to add more (for instance, in [Ecto's DSL for schemas and queries](https://github.com/elixir-ecto/ecto/blob/b5dcb8d826ced7cb4c4c2ef4859b052647e66a2a/.formatter.exs)).

Worth noting that _most_ of the Elixir formatter is not configurable (like Standard), so this stands out as an exception.

**Comment by gregorw** [comment]
Thanks for your response @searls.

> I can't see how it would be possible to enforce a firm rule on this issue that wouldn't create contexts where Ruby no longer felt like Ruby.

Our principal choices are _enabling_ or _disabling_ `Style/MethodCallWithArgsParentheses`. When we disable the rule everything goes — no “standard” is enforced. Clearly, this defeats the purpose of Standard. Therefore, we should enforce the rule.

In fact, Standard should enforce as much as it can. This avoids debates about code style. So, let’s [“just pick something”](https://github.com/testdouble/standard#i-disagree-with-rule-x-can-you-change-it).

Your argument against enforcing a rule here seems vague. How does Ruby feel to you?

ps. The search term `Enabled: false` occurs 206 times in [`config/base.yml`](https://github.com/testdouble/standard/blob/main/config/base.yml). We’ve got work to do 😅.

> If one insists on enforcing ommitted parens, all sorts of normal APIs (`add(4, 5)`) will look strange in certain contexts,

Are you saying `add(4, 5)` is better (looks less strange) than `add 4, 5`? Why? Is this really an issue?

> and things like chaining method calls could result in multiple lines of git churn that'd essentially force people to rely on the auto-fixer to format their code, because it'd be too much hopping around otherwise

For a team that wants to enforce a standard style I don’t see why this would be an issue. Auto-fixer works great.

> (a secondary goal I have with Standard is that its strictures also be natural to type, front-to-back. Most Ruby I write at this point is standard-compliant before the linter runs).

There are no strictures unless we _do_ enforce a style.

> Additionally, since enforcing the presence of parens would be more popular generally
> (and especially more popular among the constituency of people who enjoy enforcing things),

How do we know?

> you'd have a lot of people unhappy about that choice.

Maybe those people prefer enforcing _something_ to _nothing_?

> On the other hand, if one insists on enforcing that parens are always included, pretty much every DSL in use today in Ruby—from minitest assertions to Rails routes to factorybot factories—would suddenly be littered with a bunch of parenthetical noise for no benefit at all beyond someone's satisfaction of knowing that there is only one true way for the syntax to be expressed. If that extreme is someone's end game, I think that beyond a certain point you'd be better off working in something like Go than Ruby.

Agreed. This is probably the worse choice/enforcement than omitting parentheses.

> Ruby's ability to express both humdrum functional APIs and naturally legible DSLs in a single, simple programming language is a remarkable strength I would hate to see diminished. I have not yet heard of an even more compelling benefit that would be realized by enforcing all method definitions/invocations to either use or not use parentheses.

We all love Ruby ❤️. The benefit would be to keep true to the purpose of Standard I would say.

When it comes to picking a style I’m glad we have already found consensus. `omit_parentheses` is preferable to `require_parentheses` because it allows all kinds of DSLs without having to use `IgnoredMethods` and `IgnoredPatterns`.

**Comment by searls** [comment]
@gregorw I appreciate your comment, but I disagree with this approach and the statement:

> Clearly, this defeats the purpose of Standard. Therefore, we should enforce the rule.

There are a lot of rules that don't add any value at all, or that Standard makes a point of not touching. The goal of Standard is to apply a series of rules that could be applied _literally everywhere_ without exception. If there is a valid use case for disabling a particular rule (authoring or consuming a DSL in this case), then it's not a good fit for Standard, because Standard is unconfigurable. We wouldn't accomplish anything by effectively outlawing an entire type of program, as this rule would for DSLs. Separately, Standard is designed to eliminate cases where disable/ignore directives are necessary—you shouldn't have to think about the tool after you've gotten the hang of it.

If you're interested in guidelines, these are the guidelines we've been using to determine which rules to enable in Standard:

1. Would generally promote Ruby code that is agreeable as conventional, more readable, less error-prone, more secure, or more performant
2. Can be applied to any of the variety of purposes people write Ruby file listings (apps, shell scripts, gems, DSLs) without creating the need for exceptions (e.g. file ignores or disable comment directives) to cover large use cases for Ruby
3. Can be written naturally, front-to-back, such that an auto-fixer is not de facto required to write Standard Ruby (e.g. no alignment rules that depend on later lines to determine the indentation of earlier lines)
4. Don't spawn infinitely more bikeshed debates by moving the goalposts from the Rule itself to the number of possible configurations people might want (for example, we don't even touch the `Metrics` department, because some people would want 3 line methods and 80 character lines, but over time others would raise entirely valid cases for longer methods and lines, creating an endless loop of debate about the "right" length of a Ruby method, etc.)
5. Don't encourage larger version control changesets (git churn) than necessary

If you see any disabled rules that you think are a good candidate and fit the above criteria, we're happy to talk to them. I don't see how this rule rises to that threshold.
