### ISSUE TITLE
fasterer vs standard

### ISSUE THREAD

**Issue by alec-c4** [testdouble/standard#323]
Hey!
I like both tools - [fasterer](https://github.com/DamirSvrtan/fasterer) and standard. But they are in conflict. For example for default puma.rb like

```ruby
max_threads_count = ENV.fetch("RAILS_MAX_THREADS", 5) { 5 }
```

they have different recommendations. Fasterer is silent, but standard is not:
```
  config/puma.rb:7:25: Style/RedundantFetchBlock: Use `fetch("RAILS_MAX_THREADS", 5)` instead of `fetch("RAILS_MAX_THREADS") { 5 }`.
``` 

and vice versa. What do you think to update your rule?

**Comment by searls** [comment]
Any two code linters are likely to conflict and it's not a goal of Standard to make sure that no other automated linter would result in a conflict. In general [rubocop-performance](https://github.com/rubocop/rubocop-performance) (which Standard incorporates) is very well-maintained and on top of new changes in Ruby, and so I would encourage you to analyze whether fasterer is doing anything to suggest performance improvements that are both still necessary as Ruby has moved forward and aren't already being made by rubocop-performance. If there are, I'd recommend that you create an issue on rubocop-performance to suggest they add it. Ultimately my only advice is you drop one tool in favor of the other, because no project can expect to prevent conflicts with conflicting tools.
