### ISSUE TITLE
Wrong whitespace correction

### ISSUE THREAD

**Issue by will** [testdouble/standard#35]
Just noticed this auto change, which seems wrong. It may be a problem with rubocop though? If so let me know, and I'll open an issue there

![image](https://user-images.githubusercontent.com/1973/49331103-0cc00d80-f54d-11e8-9e3d-0ec565b5b1f1.png)

What's weird is that the rest of the table it didn't touch, just the last one.

**Comment by searls** [comment]
If you'd asked me to guess, I would have thought standard would have eliminated all whitespace (beyond a single space) between the elements. Maybe I disabled that and now we're in a semi-poorly defined middle ground?

**Comment by danielmorrison** [comment]
I have one repo where it collapses whitespace in one hash, but not another. I haven't taken the time to figure out why. I blame Rubocop.

**Comment by danielmorrison** [comment]
Here's an example test case from said project: 

Before: 
```ruby
enum event_type: {
     thing_1:           0,
     thing_2:           1,
     longer_thing:      2,
     even_longer_thing: 3
}


config.fog_credentials = {
  provider:              'AWS',
  aws_access_key_id:     ENV['S3_ACCESS_KEY'],
  aws_secret_access_key: ENV['S3_SECRET'],
  region:                ENV['S3_REGION']
}
```

After `standardrb --fix`

```ruby
enum event_type: {
  thing_1: 0,
  thing_2: 1,
  longer_thing: 2,
  even_longer_thing: 3,
}

config.fog_credentials = {
  provider:              "AWS",
  aws_access_key_id:     ENV["S3_ACCESS_KEY"],
  aws_secret_access_key: ENV["S3_SECRET"],
  region:                ENV["S3_REGION"],
}
```

Interestingly, changing the second one to a simple variable assignment (`hash = {…`) _does_ collapse whitespace.

**Comment by JoshCheek** [comment]
I haven't looked at the original example, but @danielmorrison's is because of line 27 in config/base.yml, which says to align hashes unless those hashes are the last argument to a method call.

https://github.com/testdouble/standard/blob/14da557e62e62e1a0f6639fd748dfc8731d83707/config/base.yml#L25-L27

The example that doesn't get aligned desugars to this:

```ruby
# the method is named "fog_credentials="
config.fog_credentials=({
  provider:              'AWS',
  aws_access_key_id:     ENV['S3_ACCESS_KEY'],
  aws_secret_access_key: ENV['S3_SECRET'],
  region:                ENV['S3_REGION']
})
```

I'm guessing that `ignore_explicit` would be a better value than `always_ignore`, but don' t time to double check that this is correct right now:

```ruby
Layout/AlignHash:
  Enabled: true
  EnforcedLastArgumentHashStyle: ignore_explicit
```

Also, it leaves me kind of scratching my head about why RuboCop presents some of [these](https://docs.rubocop.org/en/latest/cops_layout/#layoutalignhash) options. It feels like they're purely about syntax where it would instead if they grouped syntax like this into semantically meaningful options. ie just because this is a syntactic possibility doesn't mean it's meaningful to anyone, so it's unnecessarily difficult to configure it correctly (eg it's not about the last arg, it's about options hashes, here the last arg is not an options hash because the method is a setter, how do we disambiguate? Because the setter version requires explicit curly braces where options hashes don't, but again, that's a lot of very low-level implementation detail to expose to someone who just wants their hashes aligned)

```ruby
# Like doesn't it feel like it should be this:
Layout/AlignHash:
  Enabled: true
  EnforcedOptionsHash: ignore

# Or this:
Layout/AlignHash:
  Enabled: true
Layout/AlignKeywordArgs:
  Enabled: true
```

**Comment by danielmorrison** [comment]
Awesome investigation @JoshCheek!
