### ISSUE TITLE
Leading dots on method chains?

### ISSUE THREAD

**Issue by tlrobrn** [testdouble/standard#37]
My case for leading dots on method chains:

1. Each line is more of a complete thought. You can read `.foo` as `perform foo on our data` but `foo.` is `apply foo (to our data depending on if the previous line has a dot at the end) and...`.
1. Less PR noise, if you add a method to the chain only that line changes.

I read code and PRs more than copy-pasting into a repl, so while I understand the value in trailing dots for that case, it doesn't have as much weight for me personally.

Thanks for this!

**Comment by searls** [comment]
Thanks for the feedback!

FWIW, I use REPLs an awful lot, and I also find trailing dots easier to read regardless of the particulars of how someone has indented their code, because I know that the end of the line isn't the terminus. I also prefer them aesthetically.

I acknowledge the point about PR noise, but IME it's qualitatively unlike adding elements to a list or a hash in that the collective meaning of the entire chain is impacted whenever a single method invocation is tacked on, so the diff churn doesn't bother me (since I'd want to expand the entire expression regardless to understand the context).

I'm going to close this because I don't think it's likely that we'll reverse this rule, but happy to see 👍 / 👎's from folks

**Comment by cflipse** [comment]
The other nice thing about leading `.` in a chain is that it makes it easy to excise _any_ part of that chain; Just delete or comment out a particular line without having to worry about whether or not the line you just removed is terminal and I have to go remove a character from the previous line.  I find this especially helpful when rapidly iterating and test driving the filters on a particular chain.
