### ISSUE TITLE
Unexpected changes with named arguments in 1.6.0 from Style/HashSyntax

### ISSUE THREAD

**Issue by danielmorrison** [testdouble/standard#375]
Looks like we have this new cop and I'm not a fan, so raising the issue here: Style/HashSyntax: Omit the hash value.

I'm getting code that looks like: 
```ruby
category = "foo"
Product.where(category: category)
```

Changing to: 

```ruby
category = "foo"
Product.where(category:)
```

On the one hand, I learned that this works! Cool that I can still have things to learn! On the other hand, it was pretty unexpected to me.

Looks like [`EnforcedShorthandSyntax: never`](https://docs.rubocop.org/rubocop/1.24/cops_style.html#enforcedshorthandsyntax-never) is what I'd vote for.

**Comment by searls** [comment]
Agree, this seems heavy-handed in practice. It's a neat trick but it doesn't make sense to force terseness on people, especially when it's so new. (I say this as someone who routinely supports way-since-EOL'd Rubies in my new code, so this seems like something I'll be late-to-the-party to).

@camilopayan, thoughts?

**Comment by darronschall** [comment]
For other folks running into this, a temporary workaround is to disable this particular cop across your entire project. In my `.standard.yml` I added:

```
# Temporarily ignore Ruby 3.1 omit hash value syntactic sugar
# see: https://github.com/testdouble/standard/issues/375
ignore:
  - '**/*':
    - Style/HashSyntax
```

**Comment by whomwah** [comment]
It also causes problems if you are using a CI matrix of Ruby versions < 3.1 in CI.

**Comment by searls** [comment]
Spoke with @camilopayan who agrees this rule is an overreach. We will cut a release ASAP that turns it off

**Comment by searls** [comment]
also, for the record, I'm not going to enable the rule with `EnforcedShorthandSyntax: never` because I think this is a spiffy new feature that allows for terseness in lots of useful cases (like when an object exists to shovel lots attributes from one thing to the next), and it'd be a shame to ban its use in standard projects

**Comment by danielmorrison** [comment]
Sounds great to me. I'm also fine not banning spiffy new things. 

You guys are awesome. Keep up the great work!

**Comment by whomwah** [comment]
Thanks for the fast turnaround 👍

**Comment by searls** [comment]
Well, shit. We don't have that option. I hadn't realized this was a tack-on to the (otherwise very important) `Style/HashSyntax` cop, and there's no option to be unopinionated about this

<img width="876" alt="Screen Shot 2022-01-07 at 10 37 50" src="https://user-images.githubusercontent.com/79303/148567600-608d7cb6-fb24-4dc1-825a-6b6ba1087a7b.png">
.

Paging @koic & @bbatsov for context here: I'd really wish for an option to say `EnforcedShorthandSyntax: either` so that neither way is enforced, while still requiring Ruby 1.9 style hash syntax. Do you think you could accommodate for that as an option in RuboCop?

**Comment by bbatsov** [comment]
Yeah, of course we can add `either` or rather `none`; we just didn't consider that someone might not care about this. You can find some context about our decision to fuse this check with the existing cop here https://github.com/rubocop/rubocop/pull/10289

**Comment by searls** [comment]
Thanks @bbatsov, I appreciate it! Please choose whatever name is more conventional, but `either` sounds good to me.

**Comment by koic** [comment]
Yeah, I've opened https://github.com/rubocop/rubocop/pull/10351 to support the new option.

**Comment by bbatsov** [comment]
@searls The new RuboCop release (1.25) that features `either` is out.

**Comment by searls** [comment]
Thank you @bbatsov! Just saw the release notification ❤️

**Comment by kaka-ruto** [comment]
You guys are sweet!
