### ISSUE TITLE
Outdated alias gem on RubyGems.org

### ISSUE THREAD

**Issue by todd-a-jacobs** [testdouble/standard#376]
Currently, the [standardrb gem](https://rubygems.org/gems/standardrb) on RubyGems.org is stuck at v1.0.0. When installing the alias gem, it attempts to install standard v1.0.0, not the current version (v1.6.0 at this time).

I would recommend either updating the alias to depend on whatever the latest version of standard currently is, or yanking the alias from RubyGems.org altogether to avoid conflicts when Bundler tries to install both 1.0.0 and 1.6.0.

**Comment by searls** [comment]
I don't understand how this is true. If someone happens to install the alias gem `standardrb` via a Gemfile, running `bundle update` will fetch the latest version of `standard`, because its [gemspec does not pin the version of `standard`](https://github.com/testdouble/standardrb/blob/main/standardrb.gemspec#L21)

**Comment by todd-a-jacobs** [comment]
I ran into this with a more complex gemspec, but after stripping it down it behaves as you describe. Closing as not reproducible.
