### ISSUE TITLE
StandardRB Forcing Double Quotes Inside Of Double Quotes

### ISSUE THREAD

**Issue by therealrodk** [testdouble/standard#397]
**What version of this package are you using?**
standard 1.1.4

**What operating system, Node.js, and npm version?**
MacOS Catalina 10.15.7
Node v16.5.0
NPM 7.19.1

**What happened?**
When I run `bundle exec standardrb --fix`, it wants to change this:
`"#{@appointment.start_at.strftime('%b %e, %Y')}, All Day"`
to this:
`"#{@appointment.start_at.strftime("%b %e, %Y")}, All Day"`

Notice that it is nesting double quotes inside double quotes.

**What did you expect to happen?**
I expected that single quotes would be allowed inside double quotes, especially when string interpolation is necessary.

**Are you willing to submit a pull request to fix this bug?**
Perhaps. I am submitting this from work, so… we'll see.

**Comment by searls** [comment]
From the perspective of the interpreter, the precedence of whatever goes inside the `#{}` is higher precedence than the surrounding `"`. As a result, `"` is safe to use and behaves the same as it would outside an interpolation directive.

Because Standard Ruby is meant to be consistent, if someone extracts a snippet of code from inside `#{}`, then it should continue to be standard-compliant when pasted into a method definition, and not require rewriting (as would be the case if single-quote `'` characters were permitted or required). As a result, this rule is behaving as we intend it to.

**Comment by therealrodk** [comment]
That makes sense. Thanks for the clarification!
