### ISSUE TITLE
Layout/EndAlignment gets this case wrong I'm pretty sure

### ISSUE THREAD

**Issue by will** [testdouble/standard#403]
On 1.8.0

```
> bundle exec standardrb --version
1.8.0
```

It's not happy with this

``` ruby
# cat a.rb
def go(foo)
  resp = case foo
         when String
           "ok"
         else
           "no"
         end

  resp + " some stuff"
end
```

```
> bundle exec standardrb a.rb
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
standard: Run `standardrb --fix` to automatically fix some problems.
  a.rb:7:10: Layout/EndAlignment: `end` at 7, 9 is not aligned with `resp = case` at 2, 2.
> bundle exec standardrb --fix a.rb
```

And wants it fixed with this
``` ruby
def go(foo)
  resp = case foo
         when String
           "ok"
         else
           "no"
  end

  resp + " some stuff"
end
```

Which I think is worse than the `else` lining up with the `case`

**Comment by searls** [comment]
Hey @will. Yeah, this is a dupe of #322. We have a PR in #324 but we don't like it as it stands.

What we want to allow with Standard is both end-aligned `when` and single-indent `when`. The RuboCop rule doesn't allow that (it's end-aligned or nothing, for this purpose), so I think we would either need to send a PR and lobby for a new mode, or add our own fork/version of the rule to have that.

The sort of unacceptable current state is that we have the rule turned off, which is why you're getting the crummy formatting you're seeing now

**Comment by will** [comment]
Ah okay thanks for pointing out the other issues, I've subscribed to them. If any PR is made on rubocop, I'll join in on saying it's a good feature that they should add :)
