### ISSUE TITLE
Editor support for Atom

### ISSUE THREAD

**Issue by searls** [testdouble/standard#45]
Talk to someone from [AtomLinter](https://atomlinter.github.io) and fork or extend [linter-rubocop](https://github.com/AtomLinter/linter-rubocop)

**Comment by tmikeschu** [comment]
👋 I'd like to work on this issue!

**Comment by searls** [comment]
TIL I can't assign people without commit bit.

**Comment by searls** [comment]
Consider yourself assigned, Mike

**Comment by tmikeschu** [comment]
Haven't made any progress on this yet (ended up in a position with less free time 😢 ). Still hoping to contribute, but if someone sees this and wants to take a stab let me know.

**Comment by martinliptak** [comment]
Actually, `standardrb` almost works with `linter-rubocop` out of the box. The only problem is the message that `standardrb` adds to `rubocop` output at the end.

```
Notice: Disagree with these rules? While StandardRB is pre-1.0.0, feel free to submit suggestions to:
  https://github.com/testdouble/standard/issues/new
```

@searls Could this be written to stderr rather than stdin? That could fix the issue because `linter-rubocop` parses only stdout.

https://github.com/AtomLinter/linter-rubocop/blob/master/src/index.js#L39

I've made a script that filters out the message and set `linter-rubocop` to use it as rubocop executable.

```
#!/bin/bash

bin/standardrb $@ | grep -v "Notice: " | grep -v "https://github.com/testdouble/standard/issues/new"
```

This is the result:

<img width="979" alt="Screenshot 2019-03-22 at 5 29 55 PM" src="https://user-images.githubusercontent.com/631534/54838109-21750c80-4cc8-11e9-9a09-344c7c13b16b.png">

Seems to be working.

**Comment by martinliptak** [comment]
<img width="1040" alt="Screenshot 2019-03-22 at 5 39 17 PM" src="https://user-images.githubusercontent.com/631534/54838714-939a2100-4cc9-11e9-910b-670c242b3653.png">

`bin/standardrb-atom` is the script that removes "Notice: ..." from the output. Writing the notice to stderr should make `standardrb` compatible with `rubocop-linter` and possibly other editors that work with `rubocop`.

**Comment by martinliptak** [comment]
Alternatively, `standardrb` could detect `--format json` and hide notice.

**Comment by rosston** [comment]
Hm, there was an issue for fixing this: https://github.com/testdouble/standard/issues/53. I was under the impression that `--format json` disabled the "Notice: ..." message now due to https://github.com/testdouble/standard/pull/55 (landed in v0.0.23).

@martinliptak Does `--format json` still show that message for you?

**Comment by searls** [comment]
Yes, make sure the gem is up-to-date! `--format json` no longer shows the notice. It was added to the standard built-in formatter quite a while ago

**Comment by martinliptak** [comment]
Thank you @rosston and @searls 

After updating the gem, standardrb works with linter-rubocop. The only thing I had to do was setting `./bin/standardrb` as command in linter-rubocop settings.

<img width="1026" alt="Screenshot 2019-03-23 at 6 31 04 PM" src="https://user-images.githubusercontent.com/631534/54869518-e5aa7780-4d99-11e9-81e7-777654a4f91b.png">

Is this something you want to add to the How do I run standard in my editor? README section?

**Comment by searls** [comment]
Yes, please send a PR!

**Comment by matt17r** [comment]
Can this be closed now? Instructions are clear and linter issues are flagged nicely.

**Comment by searls** [comment]
Sure!
