### ISSUE TITLE
No updates since rubocop 1.35.1?

### ISSUE THREAD

**Issue by bobmaerten** [testdouble/standard#474]
Hello there (Kenobi style 😄).

It seems that the gem have trouble to follow rubocop updates. An automatic GH action that keeps track of rubocop updates seems to do the job but PR are not merged (#466, #468, #469, #470) . Just to understand, what is blocking here?

**Comment by searls** [comment]
We inspect and test Rubocop releases rather exhaustively. In an effort to save Standard users' time, we take it upon ourselves as maintainers to look at every new or modified rule and decide whether it should be incorporated into Standard or otherwise alter our base config. As a result, we often batch this work up over several Rubocop releases, and it's not uncommon for Standard to lag Rubocop by a month or so, barring anything urgent (like support for a new Ruby or a bug fix that impacts Standard's ruleset significantly)

**Comment by bobmaerten** [comment]
Ok, thanks for the explanation. Cheers.
