### ISSUE TITLE
support for pre-commit?

### ISSUE THREAD

**Issue by kbroch-rivosinc** [testdouble/standard#493]
Wondering if you would consider [pre-commit](https://pre-commit.com/) support like it is done in rubocop here: https://github.com/rubocop/rubocop/blob/master/.pre-commit-hooks.yaml?

**Comment by searls** [comment]
We don't have any plans to add this support into the library. 

While it's absolutely possible to deploy git hooks for the benefit of one's own personal productivity and confidence, tools that make it easier to enforce their use in team and corporate settings makes it much more likely that they'll be used to constrain the autonomy of developers from practicing their own workflow. For example, a pre-commit hook with the intended benefit of preventing any non-standard code from being committed to the repository can have the unintended consequence of negatively impacting when and how a developer makes WIP commits or applies patches and result in them "saving their work" less often, resulting in greater risk of data loss and rework—even if they routinely squash or fixup those commits before sharing them with others.

I think it's important to be mindful of the choices our tools make in regards to features like this because they expose a path of least resistance that are more likely to lead to unintended consequences and abuse than alternatives. For example, a standalone GitHub action that runs Standard and commits code fixes for you would have the same intended benefit without disrupting the way anyone works. ([Example action](https://github.com/qrush/m/commit/6160257b3f4a0961a9a69c80199bee64425f1cb8#commitcomment-92649728)). I'd encourage low-friction approaches like that, because they have less risk of being used to constrain how you and others do your work.

**Comment by kbroch-rivosinc** [comment]
Thank you for the quick and detailed repsonse and your opinion. I am clearly on the other side of it.

I prefer to learn of formatting and lint issues ASAP and preferrable before CI so that it doesn't enter the discussion in code reviews.  I can of course do this with my own pre-commit hook repo using `standardrb`.  And for those wanting to do WIP commits I will advise `git commit --no-verify`

Thank you again for considering the feature.

**Comment by jasonkarns** [comment]
A compromise of sorts could be an entry in the standard wiki that documents how to configure standard for pre-commit. The [wiki](https://github.com/testdouble/standard/wiki) currently documents how to configure standard to run within ones IDE (which, incidentally, would provide even faster and more frictionless feedback than a pre-commit hook could). I think it would be reasonable to demonstrate pre-commit integration in the wiki, which would eliminate (or at least lessen) any implied endorsement of a particular tool.
