### ISSUE TITLE
Hash rockets

### ISSUE THREAD

**Issue by koppen** [testdouble/standard#51]
Alright, let's talk about the elephant in the room; hash rockets. I get it, the JavaScript-style hash notation with colons is popular, but I still fail to see the benefit over the good, old hash rocket.

@samphippen recently [wrote about this](https://samphippen.com/hash-rockets-are-good-actually/) and his arguments pretty much reflect [my own](https://mentalized.net/journal/2014/05/20/ruby-hash-syntax/).

I openly admit to being biased but here are the arguments as I see them:

## In favor of colons

* No need to remember different syntax when switching between different languages.
* Fewer characters typed.

## In favor of hash rockets

* Can be used for all key types.
* Keys aren't silently converted to another type.

If we're trying to define a standard set of rules for Ruby code I'd argue consistency is fairly high on the list of goals; not just consistency across projects, but consistency inside each project. Consistency across programming languages, however, is a pipe dream.

Having both `{stuff: "symbol"}` and `{stuff => "method call"}` because you have to isn't consistent.

Having `{"foo": "bar"}["foo"]` return `nil` isn't consistent.

Having `{O: :O}.inspect` return `{:O=>:O}` isn't consistent.

While I do appreciate the aesthetics of the Javascript style notation, my having to type a few extra characters just isn't worth having my hash keys changed for me behind my back.

There is, however, a political side here that should be considered. JavaScript is the popular style du jour and I believe it is used by Rails. Straying from that path might make it more difficult to gain adoption for standard. I can offer no solution to that, unfortunately.

Another issue is future proofing. Will Ruby 3 introduce breaking changes here, deprecating hash rockets, and making it possible to use colons consistently in all cases?

Also, rockets are cool 🚀

**Comment by samphippen** [comment]
@searls and I have agreed we don't need hash rockets in standard.

**Comment by searls** [comment]
Thank you for sharing your thoughts and arguments for our beloved `=>`. Funny enough, I asked Sam to write that post, because he and I have agreed on this for several years and for its first several weeks of existence, Standard enforced hashrocket usage.

Then I went to RubyConf and learned:
* Very few developers I spoke with were open to using a tool enforcing hashrockets. Even if they could get behind the case of righteous consistency, the verbosity and unpopularity rubbed too many people the wrong way 
* Many young developers at the conference were pre-teens when 1.9 syntax was unveiled, and (depending on their experience) hashrocket syntax might feel really foreign and backwards, especially if it came to be seen as "here's how these olds want to force you to format your code"
* ruby-core has recently decided that in Ruby 3, support will be dropped for invoking methods with keyword arguments with implicit hashes using hashrockets. This will be a breaking change anywhere people are doing it, and there's not much way a linter could be certain whether you're calling a method that takes kwargs or an options hash.

After talking to Matz to confirm it, the last point was essentially the nail in the coffin for this tool enforcing hashrockets, since the last thing any of us want to do is set people up to have code that breaks when a new Ruby comes out. That wouldn't be very standard.

**Comment by koppen** [comment]
I'm the olds 😢 

It was worth a shot - at least the discussion is now here for posterity. Cheers!

**Comment by searls** [comment]
We are all the olds, @koppen 💚
