### ISSUE TITLE
Add a way to see if changes are needed

### ISSUE THREAD

**Issue by edwardloveall** [testdouble/standard#54]
We were looking to integrate this into our CI suite as a "is formatting needed?" check, but we couldn't figure out a clean way to do that. I think it would be useful if we could enforce the style guide by making it part of the CI flow.

Crystal has a `format` tool that uses a `--check` option for this which returns a non-zero exit code if any formatting/linting is necessary, but doesn't actually do formatting itself:

https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/command/format.cr#L26

That's one way to go about it, but whatever the solution I think it would be useful to have a way to fail CI if formatting is needed.

**Comment by searls** [comment]
If you don't mind the error output printing, you could just run `standardrb`.

**Comment by searls** [comment]
If you _do_ want to get a totally silent check, you could (1) implement #53 real quick, and then (2) run `standardrb -f quiet -o /dev/null`

**Comment by searls** [comment]
(After we have that working, adding a --silent flag seems like a good idea)

**Comment by jutonz** [comment]
Hm I think the issue is that if running `standardrb` results in something being corrected, it still returns an exit code of 0. This makes sense in dev, but on CI you'd just end up with files changed without an indication to the dev that they forgot to run `standardrb` themselves. 

I suppose you could run `git diff` or something and see if there are unstaged changes, but it would be super handy you could just run `standardrb --check` (or `--check-formatted` as the elixir [formatter](https://hexdocs.pm/mix/master/Mix.Tasks.Format.html#module-task-specific-options) uses) and have it just exit with nonzero if there are issues.

**Comment by searls** [comment]
I don't understand why you wouldn't just run `standardrb` without the `--fix` flag in that case, @jutonz. It's not like autofixing is doing you any good in CI if your intention is for it to fail the build.

**Comment by edwardloveall** [comment]
I did some more digging and I missed that in our setup we had `fix: true` set. This caused `standardrb` and `standardrb --fix` to act identically, which made me think there wasn't a way to check for changes without making them (and to get a non-zero exit code).

Apologies for the misunderstanding on my part (@jutonz and I are on the same project). I think either passing rubocop flags (`./bin/standardrb --fail-level=A`) or using your proposed solution here 
https://github.com/testdouble/standard/issues/54#issuecomment-450038589 should work great for now! 😄 

I think something like a `--check` flag could still be worth it to override a `fix: true` configuration explicitly for this purpose. Does that make sense @searls? Do you think that would be a useful feature?

**Comment by edwardloveall** [comment]
Cool, yeah that's exactly what I'd hope for. Sorry again for the misunderstanding. 🙂

**Comment by searls** [comment]
Feel free to implement `--dont-fix` for the benefit of future travelers :)
