### ISSUE TITLE
Disable ruby19_no_mixed_keys for Rails routes.rb?

### ISSUE THREAD

**Issue by andyw8** [testdouble/standard#70]
I would like to use Ruby 1.9 hash syntax everywhere, but for a Rails app that doesn't seem possible for some `routes.rb` entries, e.g.

`get "contact" => "pages#contact", as: "contact"`

I wonder if it would make sense to allow mixed keys for this file only?

**Comment by twe4ked** [comment]
You could rewrite that as:

```ruby
get "contact" => "pages#contact", :as => "contact"
```

**Comment by andyw8** [comment]
I could, but I would prefer use 1.9 syntax everywhere for consistency, except for places where Rails prevents it.

The Rails docs also follow this convention:
https://guides.rubyonrails.org/routing.html

**Comment by andyw8** [comment]
I *could* do this though...

```
get "contact", to: "pages#contact", as: "contact"
```

**Comment by twe4ked** [comment]
> except for places where Rails prevents it.

I guess I was just pointing out that Rails isn't preventing it. Sounds like you're well aware of the other options but others reading may not be.

I don't have any strong feelings around disabling the rule for this file, but I'm also weary of adding more special cases just for Rails.

**Comment by andyw8** [comment]
Yeah, perhaps it would be better to exclude this file completely, since it's more of a DSL than typical Ruby.

**Comment by searls** [comment]
We don't currently (to my knowledge) have any rails-specific rules or exemptions in place, and barring pretty extreme cases I'd like to keep it this way (**correction: we have one, for `db/schema.rb`, which we ignore since it's both generated and should be regenerate-able without file churn**). 

That this particular usage doesn't jive with the rails docs is unfortunate, but given that in practice I almost always see the `to:` form, I'm not very worried about it. Naturally, standard is going to disagree with some code out there, even framework recommended or generated code, and that's fine. Especially since things like this are auto-correctable.

Honestly reading this thread I'd be more inclined to suggest sending a PR to the Rails guides to make it consistent by adding `to:`.

Gonna close this for now based on this but I'm still open to more feedback if anyone feels really strongly.

**Comment by andyw8** [comment]
> Honestly reading this thread I'd be more inclined to suggest sending a PR to the Rails guides to make it consistent by adding to:.

Let's see what happens!

https://github.com/rails/rails/pull/35136

**Comment by andyw8** [comment]
Yay, it got merged.
