### ISSUE TITLE
Set EnforcedLastArgumentHashStyle to ignore_implicit on Layout/AlignHash

### ISSUE THREAD

**Issue by tomchipchase** [testdouble/standard#87]
The current setting conflicts with the arguments put forward in #83, and the setting for AlignParameters.

Currently, this is valid:
```
foo arg, opt1: bar,
         opt2: baz
```

Whereas the following would be more inline with the other alignment settings:
```
foo arg, opt1: bar,
  opt2: baz
```

**Comment by searls** [comment]
Can you point to a specific setting change that would achieve the outcome you've described? I can't see it.

`Layout/AlignParameters` is defined [here](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutalignparameters), but we already have `EnforcedStyle: with_fixed_indentation` in our [rubocop config](https://github.com/testdouble/standard/blob/master/config/base.yml#L32)

I suspect the issue in your example is due to the final parameter being a hash. Because currently standard will correct this:

```ruby
bingo foo, bar,
      baz
```

to: 

```ruby
bingo foo, bar,
  baz
```

**Comment by tomchipchase** [comment]
Its the AlignHash, rather than the AlignParameters cop that is doing it.

I think:
```
Layout/AlignHash:
  EnforcedLastArgumentHashStyle: :ignore_implicit
```
would acheive it.

**Comment by stephen-apto** [comment]
is there an update on this issue? i'm trying to understand how both parameter definitions and invocations  should be formatted. based on the HashAligment cop, i'm seeing the following:
```
def bingo(foo:, bar:, baz:)
end

# elsewhere in the code
bingo(foo: foo,
          bar: bar,
          baz: baz)
```

is that how it should look? or rather should things be left aligned:
```
bingo(foo: foo,
  bar: bar,
  baz: baz)
```

**Comment by searls** [comment]
@tomchipchase suggested `ignore_implicit` but that doesn't make sense to me since it'd be turning the rule off for half of cases, when it sounds like what we want is for the rule to behave differently

Right now `EnforcedLastArgumentHashStyle` is set to `always_inspect` and indeed fails to correct the case that @stephen-apto has above (the latter example is what we would prefer standard do). Setting it to `ignore_implicit` similarly does not result in the call's indentation being fixed AFAICT

Anyone know what setting will produce this outcome?

**Comment by jmkoni** [comment]
I did a little test with all the examples posted and `always_inspect` and `ignore_implicit` both result in this:
```
   1   │ def bingo(foo:, bar:, baz:)
   2   │ end
   3   │
   4   │ # elsewhere in the code
   5   │ bingo(foo: foo,
   6   │       bar: bar,
   7   │       baz: baz)
   8   │
   9   │ bingo(foo: foo,
  10   │       bar: bar,
  11   │       baz: baz)
  12   │
  13   │ bingo foo, bar,
  14   │   baz
  15   │
  16   │ foo arg, opt1: bar,
  17   │          opt2: baz
  ```

**Comment by camilopayan** [comment]
The examples in this issue are all left-aligned as discussed. Not sure when that changed!

**Comment by stephen-apto** [comment]
@camilopayan i think you should reread the issue. there are different formats that are accepted with the same configuration --it's the antithesis of "standard"
