### ISSUE TITLE
Proposal: Style/FormatStringToken

### ISSUE THREAD

**Issue by grantbdev** [testdouble/standard#90]
I noticed that [`Style/FormatStringToken`](https://rubocop.readthedocs.io/en/latest/cops_style/#styleformatstringtoken) is currently not enabled. I think it is a reasonable nudge for consistency, so if there is consensus on a style then maybe it should be enabled. I am not sure which style is most commonly used and I don't write code where this is applied often.

I am not a fan of `unannotated`. I have preferred `template` in the past because it's a character shorter per token than `annotated`, but looking at the [Ruby docs](https://ruby-doc.org/core-2.6.1/Kernel.html#method-i-format) I see there is more functionality available if annotated tokens are used so I could go either way:

> %<name>s style uses format style, but %{name} style doesn't.
> Examples:
```ruby
sprintf("%<foo>d : %<bar>f", { :foo => 1, :bar => 2 })
  #=> 1 : 2.000000
sprintf("%{foo}f", { :foo => 1 })
  # => "1f"
```

**Comment by searls** [comment]
I'm sorry, but I'm just as partial to unannotated (both b/c less typing and b/c a good format string has at most one variable IMO).

Because which is the best fit is almost entirely a function of how long the string is and how many substitutions are necessary, I don't think an across the board style rule is appropriate.
