### ISSUE TITLE
Proposal: Style/SignalException

### ISSUE THREAD

**Issue by grantbdev** [testdouble/standard#91]
[`Style/SignalException`](https://rubocop.readthedocs.io/en/latest/cops_style/#stylesignalexception) seems like a good cop that is currently not enabled. I don't have a strong opinion on which style should be used. As a data point, my team currently uses `only_fail` but I am not sure why 😅

**Comment by grantbdev** [comment]
Hm, I just noticed this proposal might be against some of the points made here: https://github.com/testdouble/standard/pull/39#issuecomment-445465868 + https://github.com/testdouble/standard/pull/39#issuecomment-445476593

A strong point to me is the possibility of false positives if someone decided to define their own `#fail` or `#raise` methods 🤷‍♂️ 

> To be honest I think it's a little bizarre for a linter to push people to invoke different methods or avoid an alias. The reason behind this feeling, I think, is because it seems pretty presumptive to say "no, user, you may have meant to say inject but I we are all using reduce now", especially because Standard doesn't give them a way to opt out.

This feels sorta true to me, but it's also kind of the point of linting and then standardizing the linting? Anything that is not covered by tooling could still become subject to bikeshedding in pairing or reviews. It can become a distraction when a codebase is not consistent even on tiny details like how exceptions are signaled. So it does seem in line with the goal of the project, although there may be a line to be defined where rules go too far against the spirit of Ruby.

**Comment by searls** [comment]
To acknowledge your closing point, if someone defines a method that shadows a Ruby built-in like `raise`, `warn`, `fail`, etc, they're gonna have a bad time. In fact, I'd probably sooner support a rule that precluded `def raise`, since I think it's reasonable to disallow redefining what are conceptually keywords.

It feels wrong to ban one of those pseudo-keywords `fail`, since it feels like we're banning parts of the language for no reason other than consistency. If `fail` was actually dangerous for some reason, then banning it via a linting rule would make sense, though.

Closing the issue, but subsequent conversation is always welcome.
