### ISSUE TITLE
Proposal: Style/ClassAndModuleChildren

### ISSUE THREAD

**Issue by grantbdev** [testdouble/standard#92]
[`Style/ClassAndModuleChildren`](https://rubocop.readthedocs.io/en/latest/cops_style/#styleclassandmodulechildren) is currently not enabled. I was persuaded by the [style guide](https://github.com/rubocop-hq/ruby-style-guide#namespace-definition) in favor of the `nested` style.

**Comment by searls** [comment]
I don't feel like this rule can be applied across the board and be the best thing for the readability of the codebase. 

Suppose you're striving to impose 80 character limits, but also have a very large system with a taxonomy of objects that is (appropriately) deeply nested, like:

```ruby
module Organism
  module Animal
    module Canine
      module Dog
        class ShibaInu
          def bark
            puts "woof"
          end
        end
      end
    end
  end
end
```

In a situation like this one, it's very likely that the maintainers of a codebase like this would gladly accept the tradeoff of being careful about the order in which `require` is invoked to avoid this level of indentation in every code listing (and perhaps doubly-so in unit tests, because it stands to reason you'll have required the subject under test before you define `class Organism::Animal::Canine::Dog::ShibaInuTest`, and because Ruby tests often lead to multiple levels of nesting to mirror the conditionality of the code under test)

As a result of all this, enforcing a rule like this one while also having any team-wide goals about max-characters-per-line could lead to untenable positions where a particular taxonomy of objects isn't feasible, because a method definition might only have 10 to 20 characters of width to work with. (Relatedly: this is why Standard disables line enforcement, because exceptional cases are plentiful and reasonable people can differ on what's best based on the context of a project)

Closing this for the above reasons, but subsequent conversation is always welcome.
