### ISSUE TITLE
And/Or when returning from a Rails controller

### ISSUE THREAD

**Issue by jasoncharnes** [testdouble/standard#93]
👋 I'm enjoying using Standard on a project outside of my day job. Thank you for taking the time to work on a project like this. It's something I've long wanted, but haven't found a tool that fits me and I think this is it.

@ideasasylum recently ran `standardrb --fix` on our codebase at work (in a separate branch.) We ran into an issue that would break one of our controller flows. I think this goes deeper to a Rubocop issue but nonetheless wanted to bring it up to get feedback.

We have this line in our codebase: `redirect_to watch_course_path(current_course) and return`

That code is turned into `redirect_to(watch_course_path(current_course)) && return` 

As a law-abiding Ruby citizen, I've tried to change `and` to `&&` in this line in the past. However, we have multiple `redirect_to`s or `render`s that can break us out of this controller. Rails will only return in this scenario using `and` and not `&&`. I have no doubt there is a technical reason I am just ignorant to.

We might be the minority, but I wanted to ask: is this something that can be avoided using standard? 

❤️ Thank you again for everything. 🙏

**Comment by jasonkarns** [comment]
> Rails will only return in this scenario using and and not &&

You’re correct, there is a technical reason, and it’s a subtle one that's easy to miss:

`and` and `&&` are not synonyms, but actually have different parsing precedence.

I would double check the cases you previously attempted to change manually. It's possible that there were some parenthesis that didn't get added. Converting `and` to `&&` is a strictly safe conversion _if parenthesis are added to preserve the initial precedence ordering_.

Given the same example above: `redirect_to watch_course_path(current_course) and return`; replacing `and` with `&&` will fail if the parenthesis aren't added:

`redirect_to watch_course_path(current_course) && return` evaluates to `redirect_to(watch_course_path(current_course) && return)`

But you'll note that the rubocop autofix preserves the original precedence ordering by ensuring the `redirect_to` is invoked first before returning.

If you have an aesthetic distaste for the `&&` form, you could also convert it to:

`return if redirect_to watch_course_path(current_course)`

Personally, I might try to refactor to a different form that doesn't make it conditional on the return value of `redirect_to`. Since the redirect is essentially a side effect, I wouldn't want to rely on it always being a truthy value.

**Comment by jasoncharnes** [comment]
This makes way more sense. Thank you for your time and a thorough explanation!

Aside: I'll never get over how close our names our. I'm just going always to assume we're related even though there's thorough evidence we're not.

**Comment by jasonkarns** [comment]
> I'll never get over how close our names our

Indeed! My initial (joking, of course) reaction in slack when the issue popped up:

![image](https://user-images.githubusercontent.com/119972/53749497-7fef5d80-3e75-11e9-83fc-f5b676a35837.png)

**Comment by ideasasylum** [comment]
Coupled with the fact that @jasoncharnes has a habit of changing his user name in Slack, I was waaaayyyyy confused about who I was getting these notifications from 🤣 

I think we've already started refactoring out the use of `and` for control flow but good to have this issue to add to the warnings that some Rubocop refactorings are unsafe

**Comment by jasonkarns** [comment]
Just to be clear here, the rubocop refactoring is 100% safe because it accounts for the precedence difference of the operators.

It's only when this refactoring is attempted by hand that one need be extra careful to not subtly change the effect of the expression.
